'''
Stubs generated by PyStubbler version [1.0.0.0]
Date: Monday, 01 December 2025 23:55

Namespace: Planum.DAL

In Assembly: Planum.DAL

'''

__all__ = ['Model']
from typing import Tuple, Set, Iterable, List, overload, Dict, Callable, Any
from .Model import CalcElementInfo, CellArea, DrillThroughInfo, CubeInfo, RuleInfo, CellValue, LockInfo, SplashType, DatabaseInfo, ElementInfo, CubeType, DimensionType, DimensionInfo, ElementType, DFilterMode, OlapUserInfo, ViewParams, ServerInfo



class AdvancedFilter:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Class Methods
    def Clone(self) -> AdvancedFilter: ...

    def CsvSerialize(self) -> str: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class Agreement:
#Constructors
    def __init__(self, database: Database, nameApp: str): ...

#Class Methods
    def SetStatus(self, path: List[Any], status: str) -> None: ...



class AsIsParameter:
#Instance variables (non-static)
    Value: str

#Constructors
    def __init__(self, value: str): ...

#Class Methods


class AttributeFilter(AdvancedFilter):
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @MultiFlags.setter
    def MultiFlags(self) -> AttributeFilterFlag: ...

    @MultiFlags.setter
    def MultiFlags(self, value: AttributeFilterFlag) -> None: ...

    @property
    @Flags.setter
    def Flags(self) -> AttributeFilterFlag: ...

    @Flags.setter
    def Flags(self, value: AttributeFilterFlag) -> None: ...

    @property
    @Alias1.setter
    def Alias1(self) -> str: ...

    @Alias1.setter
    def Alias1(self, value: str) -> None: ...

    @property
    @Alias2.setter
    def Alias2(self) -> str: ...

    @Alias2.setter
    def Alias2(self, value: str) -> None: ...

    @property
    @Names.setter
    def Names(self) -> List[str]: ...

    @Names.setter
    def Names(self, value: List[str]) -> None: ...

    @property
    @FilterExpression.setter
    def FilterExpression(self) -> List[AttributeFilterFilterExpression]: ...

    @FilterExpression.setter
    def FilterExpression(self, value: List[AttributeFilterFilterExpression]) -> None: ...


#Class Methods
    @overload
    def Clone(self) -> AttributeFilter: ...

    def CsvSerialize(self) -> str: ...

    @staticmethod
    def op_Implicit(plf: AttributeFilter) -> str: ...



class AttributeFilterFilterExpression:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, expressions: Iterable[str]): ...

    @overload
    def __init__(self, expressions: List[str]): ...

#Properties
    @property
    @Expressions.setter
    def Expressions(self) -> List[ExpressionStatement]: ...

    @Expressions.setter
    def Expressions(self, value: List[ExpressionStatement]) -> None: ...


#Class Methods
    def Clone(self) -> AttributeFilterFilterExpression: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class AttributeFilterFlag(Enum):
    SEARCH_ONE = 1
    SEARCH_TWO = 2
    HIDE_DOUBLE = 4
    DISPLAY_ALIAS = 8
    USE_FILTEREXP = 16


class AxeElement:
#Constructors
    def __init__(self, dimension: str, zeroSuppress: int): ...

#Properties
    @property
    @Dimension.setter
    def Dimension(self) -> str: ...

    @property
    @ZeroSuppress.setter
    def ZeroSuppress(self) -> int: ...

    @ZeroSuppress.setter
    def ZeroSuppress(self, value: int) -> None: ...


#Class Methods
    def ToString(self) -> str: ...



class CalcResult:
#Instance variables (non-static)
    Pages: List[CalcElementInfo]
    Rows: List[List[CalcElementInfo]]
    Columns: List[List[CalcElementInfo]]
    Area: List[CellArea]
    rowsTotal: Any
    colsTotal: Any

#Constructors
    def __init__(self): ...

#Class Methods


class CartesianHelper:
#Class Methods
    @staticmethod
    def CartesianProduct(sequences: Iterable[Iterable[Any]]) -> Iterable[Iterable[Any]]: ...



class Cell:
#Constructors
    def __init__(self, database: Database): ...

#Class Methods
    @overload
    def DrillThrough(self, cube: Any, path: List[Any], mode: int) -> List[DrillThroughInfo]: ...

    @overload
    def DrillThrough(self, cubeName: str, path: List[str], mode: int) -> List[DrillThroughInfo]: ...



class CompareOperator(Enum):
    NONE = 0
    GE = 1
    LE = 2
    GT = 3
    LT = 4
    EQ = 5
    NE = 6


class CompareStatement:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, operation: CompareOperator, operand: str): ...

#Properties
    @property
    @CompareOperator.setter
    def CompareOperator(self) -> CompareOperator: ...

    @CompareOperator.setter
    def CompareOperator(self, value: CompareOperator) -> None: ...

    @property
    @CompareOperand.setter
    def CompareOperand(self) -> str: ...

    @CompareOperand.setter
    def CompareOperand(self, value: str) -> None: ...


#Class Methods
    def Clone(self) -> CompareStatement: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class CsvIgnoreAttribute:
#Constructors
    def __init__(self, ignore: bool): ...

#Properties
    @property
    @Ignore.setter
    def Ignore(self) -> bool: ...

    @Ignore.setter
    def Ignore(self, value: bool) -> None: ...


#Class Methods


class CsvReaderExtensions:
#Class Methods
    @staticmethod
    def AddConverter(targetType: Any, converter: ITypeConverter) -> None: ...

    @staticmethod
    def GetConverters() -> Iterable[ITypeConverter]: ...

    @staticmethod
    def GetRecord(reader: Any) -> Any: ...

    @staticmethod
    def GetRecords(reader: Any) -> Iterable[Any]: ...

    @staticmethod
    def TryGetField(reader: Any, idx: int) -> Tuple[bool, Any]: ...



class Cube:
#Constructors
    @overload
    def __init__(self, database: Database, info: CubeInfo): ...

    @overload
    def __init__(self, database: Database, cubeId: Any): ...

    @overload
    def __init__(self, database: Database, cubeName: str): ...

#Properties
    @property
    @database.setter
    def database(self) -> Database: ...

    @database.setter
    def database(self, value: Database) -> None: ...

    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> CubeInfo: ...

    @property
    @CubePath.setter
    def CubePath(self) -> str: ...


#Class Methods
    def CellExport(self, area: List[List[Any]], path: List[Any], use_rules: bool, base_only: bool, skip_empty: bool, show_rule: bool, blocksize: Any) -> Iterable[CellArea]: ...

    @overload
    def ClearArea(self, elements: List[str]) -> CubeInfo: ...

    @overload
    def ClearArea(self, elements: Iterable[List[str]]) -> CubeInfo: ...

    @overload
    def ClearArea(self, elements: List[Any]) -> CubeInfo: ...

    @overload
    def ClearArea(self, elements: Iterable[List[Any]]) -> CubeInfo: ...

    @overload
    def ClearArea(self, elements: List[List[int]]) -> CubeInfo: ...

    @overload
    def ClearArea(self, elements: List[List[str]]) -> CubeInfo: ...

    def ClearCache(self) -> bool: ...

    def ClearComplete(self) -> CubeInfo: ...

    def CommitLock(self, lockId: Any) -> bool: ...

    @overload
    def CopyValue(self, pathTo: List[Any], pathFrom: List[Any], value: Any, withRule: bool) -> bool: ...

    @overload
    def CopyValue(self, pathTo: List[str], pathFrom: List[str], value: Any, withRule: bool) -> bool: ...

    @overload
    def CopyValue(self, pathTo: List[Any], replacementExpression: str, value: Any, withRule: bool) -> bool: ...

    @overload
    def CopyValue(self, pathTo: List[Any], pathFrom: List[Any], value: Any, withRule: bool) -> bool: ...

    def CreateRule(self, definition: str, comment: str, active: bool, position: float) -> RuleInfo: ...

    def CubeDimensions(self) -> List[Dimension]: ...

    def CubeRules(self) -> List[RuleInfo]: ...

    def DeleteRule(self, ruleId: Any) -> bool: ...

    def DeleteRules(self, rules: List[Any]) -> bool: ...

    def DimensionCoords(self, names: List[Any]) -> List[Any]: ...

    def DimensionsOrder(self, dimensions: List[str]) -> List[int]: ...

    def Equals(self, obj: Any) -> bool: ...

    def FormatDimIndex(self) -> int: ...

    @overload
    def GetArea(self) -> List[CellArea]: ...

    @overload
    def GetArea(self, path: List[Any]) -> CellArea: ...

    @overload
    def GetArea(self, names: List[List[str]]) -> List[CellArea]: ...

    @overload
    def GetArea(self, names: List[str]) -> List[CellArea]: ...

    @overload
    def GetArea(self, identifiersList: List[List[Any]]) -> List[CellArea]: ...

    def GetHashCode(self) -> int: ...

    @overload
    def GetValue(self, coords: List[str]) -> CellValue: ...

    @overload
    def GetValue(self, coords: List[Any]) -> CellValue: ...

    @overload
    def GetValue(self, coords: List[int]) -> CellValue: ...

    @overload
    def GetValue(self, names: List[Any]) -> CellValue: ...

    @overload
    def GetValue(self, coords: List[Any], dimensions: List[Any]) -> CellValue: ...

    @overload
    def GetValues(self, coords: List[List[int]]) -> List[CellValue]: ...

    @overload
    def GetValues(self, coords: Iterable[List[str]]) -> List[CellValue]: ...

    @overload
    def GetValues(self, names: Iterable[List[Any]]) -> List[CellValue]: ...

    @overload
    def GetValues(self, coords: List[List[str]]) -> List[CellValue]: ...

    @overload
    def GetValues(self, coords: Iterable[List[Any]]) -> List[CellValue]: ...

    @overload
    def GetValuesWithFormats(self, names: List[List[Any]]) -> List[CellValue]: ...

    @overload
    def GetValuesWithFormats(self, coords: List[List[Any]]) -> List[CellValue]: ...

    def GlobalViews(self) -> Iterable[str]: ...

    def Info(self, waitAllWriteOperations: bool) -> CubeInfo: ...

    def IsConsolidatedValue(self, args: List[Any]) -> bool: ...

    def IsFreezed(self, args: List[Any]) -> bool: ...

    def Load(self) -> CubeInfo: ...

    def LockArea(self, coords: Iterable[List[Any]]) -> LockInfo: ...

    def Locks(self) -> List[LockInfo]: ...

    def ParseRule(self, definition: str) -> str: ...

    def PrivateViews(self) -> Iterable[str]: ...

    def PropertiesCube(self) -> Cube: ...

    def Rename(self, newname: str) -> CubeInfo: ...

    def ResetRuleCounters(self) -> None: ...

    def RightsCube(self) -> Cube: ...

    def RollbackLock(self, lockId: Any, steps: Any) -> bool: ...

    def RuleInfo(self, ruleId: Any) -> RuleInfo: ...

    @overload
    def RuleModify(self, rule: RuleInfo) -> RuleInfo: ...

    @overload
    def RuleModify(self, ruleId: Any, definition: str, comment: str, active: Any, position: Any) -> RuleInfo: ...

    def RuleMove(self, ruleId: Any, position: float) -> RuleInfo: ...

    def Save(self) -> CubeInfo: ...

    @overload
    def SetValue(self, value: Any, names: List[str], add: bool, splash: SplashType, locale: Any) -> bool: ...

    @overload
    def SetValue(self, value: Any, coords: List[int], add: bool, splash: SplashType, locale: Any) -> bool: ...

    @overload
    def SetValue(self, value: Any, coords: List[Any], add: bool, splash: SplashType, locale: Any) -> bool: ...

    @overload
    def SetValue(self, value: Any, names: List[Any], add: bool, splash: SplashType, locale: Any) -> bool: ...

    @overload
    def SetValuesBulk(self, values: List[Any], coords: List[List[str]], locale: Any) -> bool: ...

    @overload
    def SetValuesBulk(self, values: Iterable[Any], coords: Iterable[List[str]], locale: Any) -> bool: ...

    @overload
    def SetValuesBulk(self, values: List[Any], coords: List[List[int]], locale: Any) -> bool: ...

    @overload
    def SetValuesBulk(self, values: List[Any], coords: List[List[int]], add: bool, splash: SplashType, locale: Any) -> bool: ...

    @overload
    def SetValuesBulk(self, values: Iterable[Any], coords: Iterable[List[Any]], add: bool, splash: SplashType, locale: Any) -> bool: ...

    def SetView(self, storedName: str, cubeView: CubeView, isPrivate: bool) -> bool: ...

    def Unload(self) -> CubeInfo: ...

    def View(self, storedName: str, isPrivate: bool) -> CubeView: ...



class CubeView:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @Subsets.setter
    def Subsets(self) -> List[DimensionSubset]: ...

    @property
    @Id.setter
    def Id(self) -> str: ...

    @Id.setter
    def Id(self, value: str) -> None: ...

    @property
    @Pages.setter
    def Pages(self) -> List[DimensionSubset]: ...

    @Pages.setter
    def Pages(self, value: List[DimensionSubset]) -> None: ...

    @property
    @Rows.setter
    def Rows(self) -> List[DimensionSubset]: ...

    @Rows.setter
    def Rows(self, value: List[DimensionSubset]) -> None: ...

    @property
    @Columns.setter
    def Columns(self) -> List[DimensionSubset]: ...

    @Columns.setter
    def Columns(self, value: List[DimensionSubset]) -> None: ...

    @property
    @SubsetsOrder.setter
    def SubsetsOrder(self) -> List[str]: ...

    @SubsetsOrder.setter
    def SubsetsOrder(self, value: List[str]) -> None: ...

    @property
    @AutoRefresh.setter
    def AutoRefresh(self) -> bool: ...

    @AutoRefresh.setter
    def AutoRefresh(self, value: bool) -> None: ...

    @property
    @RefreshInterval.setter
    def RefreshInterval(self) -> int: ...

    @RefreshInterval.setter
    def RefreshInterval(self, value: int) -> None: ...

    @property
    @WrapHeaders.setter
    def WrapHeaders(self) -> bool: ...

    @WrapHeaders.setter
    def WrapHeaders(self, value: bool) -> None: ...

    @property
    @Indent.setter
    def Indent(self) -> bool: ...

    @Indent.setter
    def Indent(self, value: bool) -> None: ...

    @property
    @ColumnWidth.setter
    def ColumnWidth(self) -> Any: ...

    @ColumnWidth.setter
    def ColumnWidth(self, value: Any) -> None: ...

    @property
    @FreezePanes.setter
    def FreezePanes(self) -> bool: ...

    @FreezePanes.setter
    def FreezePanes(self, value: bool) -> None: ...

    @property
    @Styleset.setter
    def Styleset(self) -> str: ...

    @Styleset.setter
    def Styleset(self, value: str) -> None: ...

    @property
    @Label.setter
    def Label(self) -> str: ...

    @Label.setter
    def Label(self, value: str) -> None: ...

    @property
    @CubeName.setter
    def CubeName(self) -> str: ...

    @CubeName.setter
    def CubeName(self, value: str) -> None: ...

    @property
    @CubeId.setter
    def CubeId(self) -> Any: ...

    @CubeId.setter
    def CubeId(self, value: Any) -> None: ...

    @property
    @DatabaseName.setter
    def DatabaseName(self) -> str: ...

    @DatabaseName.setter
    def DatabaseName(self, value: str) -> None: ...

    @property
    @ZeroSuppressInRows.setter
    def ZeroSuppressInRows(self) -> bool: ...

    @ZeroSuppressInRows.setter
    def ZeroSuppressInRows(self, value: bool) -> None: ...

    @property
    @ZeroSuppressInColumns.setter
    def ZeroSuppressInColumns(self) -> bool: ...

    @ZeroSuppressInColumns.setter
    def ZeroSuppressInColumns(self, value: bool) -> None: ...


#Class Methods
    def Clone(self) -> CubeView: ...

    @staticmethod
    def CreateView(cube: Cube) -> CubeView: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...

    def TranspositionPRC(self) -> List[int]: ...



class Database:
#Constructors
    @overload
    def __init__(self, server: Server, databaseInfo: DatabaseInfo): ...

    @overload
    def __init__(self, server: Server, databaseId: Any): ...

    @overload
    def __init__(self, server: Server, databaseName: str): ...

#Properties
    @property
    @Server.setter
    def Server(self) -> Server: ...

    @Server.setter
    def Server(self, value: Server) -> None: ...

    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> DatabaseInfo: ...


#Class Methods
    def CellProperties(self) -> List[ElementInfo]: ...

    @overload
    def CreateCube(self, cubeName: str, dimensions: Iterable[Dimension], type: CubeType) -> Cube: ...

    @overload
    def CreateCube(self, cubeName: str, dimensions: List[Dimension], type: CubeType) -> Cube: ...

    @overload
    def CreateCube(self, cubeName: str, dimensions: Iterable[str], type: CubeType) -> Cube: ...

    @overload
    def CreateCube(self, cubeName: str, dimensions: List[str], type: CubeType) -> Cube: ...

    @overload
    def CreateCube(self, cubeName: str, dimensions: Iterable[Any], type: CubeType) -> Cube: ...

    @overload
    def CreateCube(self, cubeName: str, dimensions: List[Any], type: CubeType) -> Cube: ...

    def CreateDimension(self, dimensionName: str, type: DimensionType) -> Dimension: ...

    @overload
    def Cube(self, cubeName: str) -> Cube: ...

    @overload
    def Cube(self, cubeId: Any) -> Cube: ...

    @overload
    def Cube(self, cubeInfo: CubeInfo) -> Cube: ...

    @overload
    def CubeInfo(self, cubeName: str) -> CubeInfo: ...

    @overload
    def CubeInfo(self, cubeId: Any) -> CubeInfo: ...

    def CubeInfos(self) -> List[CubeInfo]: ...

    def Cubes(self) -> List[Cube]: ...

    @overload
    def DeleteCube(self, cube: Cube) -> bool: ...

    @overload
    def DeleteCube(self, cubeId: Any) -> bool: ...

    @overload
    def DeleteDimension(self, dimension: Dimension) -> bool: ...

    @overload
    def DeleteDimension(self, dimId: Any) -> bool: ...

    @overload
    def Dimension(self, dimName: str) -> Dimension: ...

    @overload
    def Dimension(self, dimId: Any) -> Dimension: ...

    @overload
    def Dimension(self, dimensionInfo: DimensionInfo) -> Dimension: ...

    @overload
    def DimensionInfo(self, dimId: Any) -> DimensionInfo: ...

    @overload
    def DimensionInfo(self, dimname: str) -> DimensionInfo: ...

    def DimensionInfos(self) -> List[DimensionInfo]: ...

    def Dimensions(self) -> List[Dimension]: ...

    def DisableMarkers(self) -> bool: ...

    def EnableMarkers(self) -> bool: ...

    def Equals(self, obj: Any) -> bool: ...

    def GetHashCode(self) -> int: ...

    def GetPicklist(self, property: str) -> Iterable[str]: ...

    def GlobalSubsets(self) -> Iterable[str]: ...

    def GlobalViews(self) -> Iterable[str]: ...

    def Info(self) -> DatabaseInfo: ...

    def Load(self) -> DatabaseInfo: ...

    def PrivateViews(self, userName: str) -> Iterable[str]: ...

    def Rename(self, new_name: str) -> DatabaseInfo: ...

    def Save(self, complete: bool, backupPath: str) -> DatabaseInfo: ...

    def Unload(self) -> DatabaseInfo: ...



class DataFilter(AdvancedFilter):
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @MultiFlags.setter
    def MultiFlags(self) -> DataFilterFlag: ...

    @MultiFlags.setter
    def MultiFlags(self, value: DataFilterFlag) -> None: ...

    @property
    @Flags.setter
    def Flags(self) -> DataFilterFlag: ...

    @Flags.setter
    def Flags(self, value: DataFilterFlag) -> None: ...

    @property
    @Cube.setter
    def Cube(self) -> str: ...

    @Cube.setter
    def Cube(self, value: str) -> None: ...

    @property
    @UseStrings.setter
    def UseStrings(self) -> bool: ...

    @UseStrings.setter
    def UseStrings(self, value: bool) -> None: ...

    @property
    @Statement1.setter
    def Statement1(self) -> CompareStatement: ...

    @Statement1.setter
    def Statement1(self, value: CompareStatement) -> None: ...

    @property
    @Statement2.setter
    def Statement2(self) -> CompareStatement: ...

    @Statement2.setter
    def Statement2(self, value: CompareStatement) -> None: ...

    @property
    @Coordinates.setter
    def Coordinates(self) -> List[DataFilterCoordinates]: ...

    @Coordinates.setter
    def Coordinates(self, value: List[DataFilterCoordinates]) -> None: ...

    @property
    @UpperPercentage.setter
    def UpperPercentage(self) -> Any: ...

    @UpperPercentage.setter
    def UpperPercentage(self, value: Any) -> None: ...

    @property
    @LowerPercentage.setter
    def LowerPercentage(self) -> Any: ...

    @LowerPercentage.setter
    def LowerPercentage(self, value: Any) -> None: ...

    @property
    @Top.setter
    def Top(self) -> int: ...

    @Top.setter
    def Top(self, value: int) -> None: ...


#Class Methods
    @overload
    def Clone(self) -> DataFilter: ...

    def CsvSerialize(self) -> str: ...

    @staticmethod
    def op_Implicit(plf: DataFilter) -> str: ...



class DataFilterCoordinates:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, elements: List[str]): ...

#Properties
    @property
    @Elements.setter
    def Elements(self) -> List[str]: ...

    @Elements.setter
    def Elements(self, value: List[str]) -> None: ...


#Class Methods
    def Clone(self) -> DataFilterCoordinates: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class DataFilterFlag(Enum):
    DATA_MIN = 1
    DATA_MAX = 2
    DATA_SUM = 4
    DATA_AVERAGE = 8
    DATA_ANY = 16
    DATA_ALL = 32
    DATA_STRING = 64
    ONLY_CONSOLIDATED = 128
    ONLY_LEAVES = 256
    UPPER_PERCENTAGE = 512
    LOWER_PERCENTAGE = 1024
    MID_PERCENTAGE = 2048
    TOP = 4096
    NORULES = 8192


class DeterminalPick:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @ElementName.setter
    def ElementName(self) -> str: ...

    @ElementName.setter
    def ElementName(self, value: str) -> None: ...

    @property
    @Childs.setter
    def Childs(self) -> List[DeterminalPick]: ...

    @Childs.setter
    def Childs(self, value: List[DeterminalPick]) -> None: ...

    @property
    @Expanded.setter
    def Expanded(self) -> bool: ...

    @Expanded.setter
    def Expanded(self, value: bool) -> None: ...


#Class Methods
    def Clone(self) -> DeterminalPick: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class Dimension:
#Constructors
    @overload
    def __init__(self, database: Database, info: DimensionInfo): ...

    @overload
    def __init__(self, database: Database, databaseId: Any): ...

    @overload
    def __init__(self, database: Database, dimensionName: str): ...

#Properties
    @property
    @Database.setter
    def Database(self) -> Database: ...

    @Database.setter
    def Database(self, value: Database) -> None: ...

    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> DimensionInfo: ...


#Class Methods
    def AttributeCube(self) -> Cube: ...

    def AttributeDimension(self) -> Dimension: ...

    @overload
    def ChangeElements(self, elements: Iterable[Any], types: Iterable[ElementType]) -> List[ElementInfo]: ...

    @overload
    def ChangeElements(self, elements: List[Any], types: List[ElementType]) -> List[ElementInfo]: ...

    @overload
    def ChangeElements(self, names: Iterable[str], types: Iterable[ElementType]) -> List[ElementInfo]: ...

    @overload
    def ChangeElements(self, names: List[str], types: List[ElementType]) -> List[ElementInfo]: ...

    def CreateElement(self, name: str, type: ElementType) -> ElementInfo: ...

    @overload
    def CreateElements(self, names: List[str], types: List[ElementType]) -> bool: ...

    @overload
    def CreateElements(self, names: Iterable[str], types: Iterable[ElementType]) -> bool: ...

    def DestroyElement(self, element: Any) -> bool: ...

    @overload
    def DestroyElements(self, elements: Iterable[str]) -> bool: ...

    @overload
    def DestroyElements(self, elements: List[str]) -> bool: ...

    @overload
    def DestroyElements(self, elements: List[Any]) -> bool: ...

    def Dfilter(self, cube: Cube, mode: DFilterMode, condition: str, top: float, upper: float, lower: float, coords: List[List[Any]]) -> List[ElementInfo]: ...

    def DimensionCubes(self) -> List[CubeInfo]: ...

    @overload
    def Element(self, info: ElementInfo) -> Element: ...

    @overload
    def Element(self, elementName: str) -> Element: ...

    @overload
    def Element(self, elementId: Any) -> Element: ...

    def ElementAlias(self, element: str, alias: str) -> str: ...

    @overload
    def ElementInfo(self, elementId: Any) -> ElementInfo: ...

    @overload
    def ElementInfo(self, nameElement: str) -> ElementInfo: ...

    @overload
    def ElementInfos(self) -> List[ElementInfo]: ...

    @overload
    def ElementInfos(self, parent: Any, skip: Any, limit: Any, element: Any) -> List[ElementInfo]: ...

    def Elements(self) -> List[Element]: ...

    def Equals(self, obj: Any) -> bool: ...

    def GetHashCode(self) -> int: ...

    def GlobalSubsets(self) -> Iterable[str]: ...

    def Info(self) -> DimensionInfo: ...

    def PrivateSubsets(self) -> Iterable[str]: ...

    def Rename(self, newname: str) -> DimensionInfo: ...

    def RightsCube(self) -> Cube: ...

    def SetSubset(self, subsetName: str, dimensionSubset: DimensionSubset, isPrivate: bool) -> bool: ...

    def Subset(self, subsetName: str, isPrivate: bool) -> DimensionSubset: ...

    def SubsetPreview(self, subset: DimensionSubset) -> List[CalcElementInfo]: ...

    def TryElementInfo(self, nameElement: str) -> Tuple[bool, Any]: ...



class DimensionFilterMode(Enum):
    SimplePick = 0
    Advanced = 1
    Stored = 2


class DimensionSubset:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, dimension: Dimension): ...

#Properties
    @property
    @EnsureSingle.setter
    def EnsureSingle(self) -> bool: ...

    @EnsureSingle.setter
    def EnsureSingle(self, value: bool) -> None: ...

    @property
    @SimplePick.setter
    def SimplePick(self) -> SubsetSimplePick: ...

    @SimplePick.setter
    def SimplePick(self, value: SubsetSimplePick) -> None: ...

    @property
    @Advanced.setter
    def Advanced(self) -> List[AdvancedFilter]: ...

    @Advanced.setter
    def Advanced(self, value: List[AdvancedFilter]) -> None: ...

    @property
    @Mode.setter
    def Mode(self) -> DimensionFilterMode: ...

    @Mode.setter
    def Mode(self, value: DimensionFilterMode) -> None: ...

    @property
    @SortSettings.setter
    def SortSettings(self) -> SortSettings: ...

    @SortSettings.setter
    def SortSettings(self, value: SortSettings) -> None: ...

    @property
    @CustomRules.setter
    def CustomRules(self) -> str: ...

    @CustomRules.setter
    def CustomRules(self, value: str) -> None: ...

    @property
    @StyleAttribute.setter
    def StyleAttribute(self) -> str: ...

    @StyleAttribute.setter
    def StyleAttribute(self, value: str) -> None: ...

    @property
    @IncudeAttributes.setter
    def IncudeAttributes(self) -> List[str]: ...

    @IncudeAttributes.setter
    def IncudeAttributes(self, value: List[str]) -> None: ...

    @property
    @Label.setter
    def Label(self) -> str: ...

    @Label.setter
    def Label(self, value: str) -> None: ...

    @property
    @SubsetId.setter
    def SubsetId(self) -> str: ...

    @SubsetId.setter
    def SubsetId(self, value: str) -> None: ...

    @property
    @DimensionName.setter
    def DimensionName(self) -> str: ...

    @DimensionName.setter
    def DimensionName(self, value: str) -> None: ...

    @property
    @DatabaseName.setter
    def DatabaseName(self) -> str: ...

    @DatabaseName.setter
    def DatabaseName(self, value: str) -> None: ...

    @property
    @StoredName.setter
    def StoredName(self) -> str: ...

    @StoredName.setter
    def StoredName(self, value: str) -> None: ...


#Class Methods
    def Clone(self) -> DimensionSubset: ...

    def GetDefinition(self) -> str: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class Element:
#Instance variables (non-static)
    dimension: Dimension

#Constructors
    def __init__(self, dimension: Dimension, info: ElementInfo): ...

#Properties
    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> ElementInfo: ...

    @property
    @Childs.setter
    def Childs(self) -> Iterable[Element]: ...

    @property
    @ChildsWeight.setter
    def ChildsWeight(self) -> Iterable[float]: ...


#Class Methods
    @overload
    def AppendChild(self, child: str, weight: float) -> ElementInfo: ...

    @overload
    def AppendChild(self, child: Any, weight: float) -> ElementInfo: ...

    @overload
    def AppendChilds(self, childs: List[Any], weights: List[float]) -> ElementInfo: ...

    @overload
    def AppendChilds(self, childs: Iterable[Any], weights: Iterable[float]) -> ElementInfo: ...

    @overload
    def AppendChilds(self, childs: List[str], weights: List[float]) -> ElementInfo: ...

    @overload
    def AppendChilds(self, childs: Iterable[str], weights: Iterable[float]) -> ElementInfo: ...

    @overload
    def AttributeValue(self, attribute: Any) -> CellValue: ...

    @overload
    def AttributeValue(self, attribute: str) -> CellValue: ...

    @overload
    def Change(self, new_type: ElementType) -> ElementInfo: ...

    @overload
    def Change(self, new_type: ElementType, childs: List[Any], weights: List[float]) -> ElementInfo: ...

    @overload
    def Change(self, new_type: ElementType, childs: List[str], weights: List[float]) -> ElementInfo: ...

    def Child(self, index: Any) -> Element: ...

    def ChildInfo(self, index: Any) -> ElementInfo: ...

    def Info(self) -> ElementInfo: ...

    def Move(self, position: Any) -> ElementInfo: ...

    def Rename(self, newName: str) -> ElementInfo: ...



class EnumHelper:
#Class Methods
    @staticmethod
    def Description(eValue: Any) -> str: ...

    @staticmethod
    @overload
    def GetAllValuesAndDescriptions() -> Iterable[ValueDescription]: ...

    @staticmethod
    @overload
    def GetAllValuesAndDescriptions(type: Any) -> Iterable[ValueDescription]: ...

    @staticmethod
    def GetDefaultValue() -> Any: ...

    @staticmethod
    def TryGetValue(description: str) -> Tuple[bool, Any]: ...



class ExpressionStatement:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, expression: str): ...

#Properties
    @property
    @Expression.setter
    def Expression(self) -> str: ...

    @Expression.setter
    def Expression(self, value: str) -> None: ...


#Class Methods
    def Clone(self) -> ExpressionStatement: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class HierarchyFilter(AdvancedFilter):
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @MultiFlags.setter
    def MultiFlags(self) -> StructuralFilterFlag: ...

    @MultiFlags.setter
    def MultiFlags(self, value: StructuralFilterFlag) -> None: ...

    @property
    @Flags.setter
    def Flags(self) -> StructuralFilterFlag: ...

    @Flags.setter
    def Flags(self, value: StructuralFilterFlag) -> None: ...

    @property
    @Indent.setter
    def Indent(self) -> int: ...

    @Indent.setter
    def Indent(self, value: int) -> None: ...

    @property
    @ElementName.setter
    def ElementName(self) -> str: ...

    @ElementName.setter
    def ElementName(self, value: str) -> None: ...

    @property
    @LevelStart.setter
    def LevelStart(self) -> int: ...

    @LevelStart.setter
    def LevelStart(self, value: int) -> None: ...

    @property
    @LevelEnd.setter
    def LevelEnd(self) -> int: ...

    @LevelEnd.setter
    def LevelEnd(self, value: int) -> None: ...

    @property
    @LevelLimit.setter
    def LevelLimit(self) -> bool: ...

    @LevelLimit.setter
    def LevelLimit(self, value: bool) -> None: ...

    @property
    @RevolveCount.setter
    def RevolveCount(self) -> Any: ...

    @RevolveCount.setter
    def RevolveCount(self, value: Any) -> None: ...


#Class Methods
    @overload
    def Clone(self) -> HierarchyFilter: ...

    def CsvSerialize(self) -> str: ...

    @staticmethod
    def op_Implicit(plf: HierarchyFilter) -> str: ...



class ICube:
#Properties
    @property
    @CubePath.setter
    def CubePath(self) -> str: ...

    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> CubeInfo: ...


#Class Methods
    @overload
    def CopyValue(self, value: Any, with_rule: bool) -> Tuple[bool, List[Any], List[Any]]: ...

    @overload
    def CopyValue(self, replacementExpression: str, value: Any, with_rule: bool) -> Tuple[bool, List[Any]]: ...

    def CubeDimensions(self) -> List[Dimension]: ...

    def GetValue(self) -> Tuple[CellValue, List[str]]: ...

    def PropertiesCube(self) -> Cube: ...

    def SetValue(self, value: Any, add: bool, splash: SplashType, locale: Any) -> Tuple[bool, List[str]]: ...



class IDatabase:
#Properties
    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> DatabaseInfo: ...


#Class Methods
    def CreateCube(self, cubeName: str, dimensions: List[Any], type: CubeType) -> Cube: ...

    def CreateDimension(self, dimensionName: str, type: DimensionType) -> Dimension: ...

    def Cube(self, cubeName: str) -> Cube: ...

    def CubeInfo(self, cubeName: str) -> CubeInfo: ...

    def CubeInfos(self) -> List[CubeInfo]: ...

    def Cubes(self) -> List[Cube]: ...

    def Dimension(self, dimName: str) -> Dimension: ...

    def DimensionInfo(self, dimname: str) -> DimensionInfo: ...

    def DimensionInfos(self) -> List[DimensionInfo]: ...

    def Dimensions(self) -> List[Dimension]: ...



class IDimension:
#Properties
    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> DimensionInfo: ...

    @property
    @Database.setter
    def Database(self) -> Database: ...


#Class Methods
    def AttributeCube(self) -> Cube: ...

    def AttributeDimension(self) -> Dimension: ...

    def CreateElement(self, name: str, type: ElementType) -> ElementInfo: ...

    def DimensionCubes(self) -> List[CubeInfo]: ...

    def Element(self, nameElement: str) -> Element: ...

    def ElementAlias(self, element: str, alias: str) -> str: ...

    def ElementInfo(self, nameElement: str) -> ElementInfo: ...

    def ElementInfos(self) -> List[ElementInfo]: ...

    def Elements(self) -> List[Element]: ...



class IElement:
#Properties
    @property
    @CurrentInfo.setter
    def CurrentInfo(self) -> ElementInfo: ...


#Class Methods
    def AppendChild(self, child: str, weight: float) -> ElementInfo: ...

    def AppendChilds(self, childs: List[str], weights: List[float]) -> ElementInfo: ...

    def AttributeValue(self, attribute: str) -> CellValue: ...

    @overload
    def Change(self, new_type: ElementType) -> ElementInfo: ...

    @overload
    def Change(self, new_type: ElementType, childs: List[str], weights: List[float]) -> ElementInfo: ...

    def Child(self, index: Any) -> Element: ...

    def ChildInfo(self, index: Any) -> ElementInfo: ...



class IndentEnum(Enum):
    Undefined = 0
    Indent = 1
    Level = 2
    Depth = 3


class IOlapConnection:
#Class Methods
    def CreateSession(self, user: str, password: str, session_name: str) -> Any: ...

    def ProcessRequest(self, olapSession: IOlapSession, olapRequest: IOlapRequest) -> Any: ...

    @overload
    def ProcessRequestAsync(self, olapSession: IOlapSession, olapRequest: IOlapRequest) -> Any: ...

    @overload
    def ProcessRequestAsync(self, olapSession: IOlapSession, olapRequest: IOlapRequest, cancellationToken: Any) -> Any: ...



class IOlapRequest:
#Properties
    @property
    @Path.setter
    def Path(self) -> str: ...

    @property
    @Timeout.setter
    def Timeout(self) -> int: ...


#Class Methods
    @overload
    def GetResponse(self) -> Any: ...

    @overload
    def GetResponse(self) -> Any: ...

    def GetResponseArray(self) -> Any: ...

    def GetResponseArrayAsync(self, cancellationToken: Any) -> Any: ...

    def GetResponseAsync(self, cancellationToken: Any) -> Any: ...



class IOlapServerException:
#Properties
    @property
    @Code.setter
    def Code(self) -> int: ...

    @property
    @Message.setter
    def Message(self) -> str: ...

    @property
    @Description.setter
    def Description(self) -> str: ...


#Class Methods


class IOlapSession:
#Properties
    @property
    @SID.setter
    def SID(self) -> str: ...

    @SID.setter
    def SID(self, value: str) -> None: ...

    @property
    @TTL.setter
    def TTL(self) -> int: ...

    @TTL.setter
    def TTL(self, value: int) -> None: ...

    @property
    @Optional.setter
    def Optional(self) -> str: ...

    @Optional.setter
    def Optional(self, value: str) -> None: ...

    @property
    @UserName.setter
    def UserName(self) -> str: ...

    @UserName.setter
    def UserName(self, value: str) -> None: ...

    @property
    @Locale.setter
    def Locale(self) -> Any: ...

    @Locale.setter
    def Locale(self, value: Any) -> None: ...


#Class Methods


class IServer:
#Class Methods
    def CreateDatabase(self, database_name: str) -> Database: ...

    def Database(self, dbName: str) -> Database: ...

    def DatabaseInfo(self, dbname: str) -> DatabaseInfo: ...

    def DatabaseInfos(self) -> List[DatabaseInfo]: ...

    def Databases(self) -> List[Database]: ...



class ITypeConverter:
#Class Methods
    def CanConvertFromString(self, input: str) -> bool: ...

    def ConvertFromString(self, input: str) -> Any: ...



class LongArrayComparer:
#Static Properties
    @property
    @staticmethod
    def Instance() -> Any: ...


#Class Methods


class OlapConnection:
#Constructors
    @overload
    def __init__(self, serverAddress: Any): ...

    @overload
    def __init__(self, httpClient: Any): ...

#Class Methods
    def CreateSession(self, user: str, password: str, session_name: str) -> Any: ...

    def ProcessRequest(self, olapSession: IOlapSession, olapRequest: IOlapRequest) -> Any: ...

    @overload
    def ProcessRequestAsync(self, olapSession: IOlapSession, olapRequest: IOlapRequest) -> Any: ...

    @overload
    def ProcessRequestAsync(self, olapSession: IOlapSession, olapRequest: IOlapRequest, cancellationToken: Any) -> Any: ...



class OlapRequest:
#Constructors
    def __init__(self, olapConnection: IOlapConnection, olapSession: IOlapSession, path: str, timeout: int, logger: Any): ...

#Properties
    @property
    @Path.setter
    def Path(self) -> str: ...

    @Path.setter
    def Path(self, value: str) -> None: ...

    @property
    @Timeout.setter
    def Timeout(self) -> int: ...

    @Timeout.setter
    def Timeout(self, value: int) -> None: ...


#Class Methods
    @overload
    def GetResponse(self) -> Any: ...

    @overload
    def GetResponse(self) -> Any: ...

    def GetResponseArray(self) -> Any: ...

    def GetResponseArrayAsync(self, cancellationToken: Any) -> Any: ...

    @overload
    def GetResponseAsync(self, cancellationToken: Any) -> Any: ...

    @overload
    def GetResponseAsync(self, cancellationToken: Any) -> Any: ...





class OlapServerException:
#Constructors
    @overload
    def __init__(self, message: str, innerException: Any): ...

    @overload
    def __init__(self, code: int, message: str, description: str, innerException: Any): ...

#Properties
    @property
    @Code.setter
    def Code(self) -> int: ...

    @Code.setter
    def Code(self, value: int) -> None: ...

    @property
    @Message.setter
    def Message(self) -> str: ...

    @property
    @Description.setter
    def Description(self) -> str: ...

    @Description.setter
    def Description(self, value: str) -> None: ...


#Class Methods
    def ToString(self) -> str: ...



class OlapServerExceptionType(Enum):
    ERROR_UNKNOWN = 1
    ERROR_INTERNAL = 2
    ERROR_ID_NOT_FOUND = 1000
    ERROR_INVALID_FILENAME = 1001
    ERROR_MKDIR_FAILED = 1002
    ERROR_RENAME_FAILED = 1003
    ERROR_AUTHORIZATION_FAILED = 1004
    ERROR_INVALID_TYPE = 1005
    ERROR_INVALID_COORDINATES = 1006
    ERROR_CONVERSION_FAILED = 1007
    ERROR_FILE_NOT_FOUND_ERROR = 1008
    ERROR_NOT_AUTHORIZED = 1009
    ERROR_CORRUPT_FILE = 1010
    ERROR_WITHIN_EVENT = 1011
    ERROR_NOT_WITHIN_EVENT = 1012
    ERROR_INVALID_PERMISSION = 1013
    ERROR_INVALID_SERVER_PATH = 1014
    ERROR_INVALID_SESSION = 1015
    ERROR_PARAMETER_MISSING = 1016
    ERROR_SERVER_TOKEN_OUTDATED = 1017
    ERROR_INVALID_SPLASH_MODE = 1018
    ERROR_WORKER_AUTHORIZATION_FAILED = 1019
    ERROR_WORKER_MESSAGE = 1020
    ERROR_API_CALL_NOT_IMPLEMENTED = 1021
    ERROR_HTTP_DISABLED = 1022
    ERROR_OUT_OF_MEMORY = 1023
    ERROR_SSL_FAILED = 1024
    ERROR_GPU_SERVER_NOT_ENABLED = 1025
    ERROR_INVALID_STRING = 1026
    ERROR_INVALID_VERSION = 1027
    ERROR_INVALID_AGGR_FUNCTION = 1028
    ERROR_INVALID_EXPAND = 1029
    ERROR_INVALID_PREDICT_FUNCTION = 1030
    ERROR_INVALID_PREDICT_AREA = 1031
    ERROR_SSO_FAILED = 1032
    ERROR_COPY_FAILED = 1033
    ERROR_ZIP = 1034
    ERROR_INVALID_DATABASE_NAME = 2000
    ERROR_DATABASE_NOT_FOUND = 2001
    ERROR_DATABASE_NOT_LOADED = 2002
    ERROR_DATABASE_UNSAVED = 2003
    ERROR_DATABASE_STILL_LOADED = 2004
    ERROR_DATABASE_NAME_IN_USE = 2005
    ERROR_DATABASE_UNDELETABLE = 2006
    ERROR_DATABASE_UNRENAMABLE = 2007
    ERROR_DATABASE_TOKEN_OUTDATED = 2008
    ERROR_INVALID_DATABASE_TYPE = 2009
    ERROR_DATABASE_BACKUP = 2010
    ERROR_DIMENSION_EMPTY = 3000
    ERROR_DIMENSION_EXISTS = 3001
    ERROR_DIMENSION_NOT_FOUND = 3002
    ERROR_INVALID_DIMENSION_NAME = 3003
    ERROR_DIMENSION_UNCHANGABLE = 3004
    ERROR_DIMENSION_NAME_IN_USE = 3005
    ERROR_DIMENSION_IN_USE = 3006
    ERROR_DIMENSION_UNDELETABLE = 3007
    ERROR_DIMENSION_UNRENAMABLE = 3008
    ERROR_DIMENSION_TOKEN_OUTDATED = 3009
    ERROR_DIMENSION_LOCKED = 3010
    ERROR_ELEMENT_EXISTS = 4000
    ERROR_ELEMENT_CIRCULAR_REFERENCE = 4001
    ERROR_ELEMENT_NAME_IN_USE = 4002
    ERROR_ELEMENT_NAME_NOT_UNIQUE = 4003
    ERROR_ELEMENT_NOT_FOUND = 4004
    ERROR_ELEMENT_NO_CHILD_OF = 4005
    ERROR_INVALID_ELEMENT_NAME = 4006
    ERROR_INVALID_OFFSET = 4007
    ERROR_INVALID_ELEMENT_TYPE = 4008
    ERROR_INVALID_POSITION = 4009
    ERROR_ELEMENT_NOT_DELETABLE = 4010
    ERROR_ELEMENT_NOT_RENAMABLE = 4011
    ERROR_ELEMENT_NOT_CHANGABLE = 4012
    ERROR_INVALID_MODE = 4013
    ERROR_CUBE_NOT_FOUND = 5000
    ERROR_INVALID_CUBE_NAME = 5001
    ERROR_CUBE_NOT_LOADED = 5002
    ERROR_CUBE_EMPTY = 5003
    ERROR_CUBE_UNSAVED = 5004
    ERROR_SPLASH_DISABLED = 5005
    ERROR_COPY_PATH_NOT_NUMERIC = 5006
    ERROR_INVALID_COPY_VALUE = 5007
    ERROR_CUBE_NAME_IN_USE = 5008
    ERROR_CUBE_UNDELETABLE = 5009
    ERROR_CUBE_UNRENAMABLE = 5010
    ERROR_CUBE_TOKEN_OUTDATED = 5011
    ERROR_SPLASH_NOT_POSSIBLE = 5012
    ERROR_CUBE_LOCK_NOT_FOUND = 5013
    ERROR_CUBE_WRONG_USER = 5014
    ERROR_CUBE_WRONG_LOCK = 5015
    ERROR_CUBE_BLOCKED_BY_LOCK = 5016
    ERROR_CUBE_LOCK_NO_CAPACITY = 5017
    ERROR_GOALSEEK = 5018
    ERROR_CUBE_IS_SYSTEM_CUBE = 5019
    ERROR_COPY_NOT_POSSIBLE = 5020
    ERROR_INVALID_CUBE_TYPE = 5021
    ERROR_DEFRAGMENTATION = 5022
    ERROR_NET_ARG = 6000
    ERROR_INV_CMD = 6001
    ERROR_INV_CMD_CTL = 6002
    ERROR_NET_SEND = 6003
    ERROR_NET_CONN_TERM = 6004
    ERROR_NET_RECV = 6005
    ERROR_NET_HS_HALLO = 6006
    ERROR_NET_HS_PROTO = 6007
    ERROR_INV_ARG_COUNT = 6008
    ERROR_INV_ARG_TYPE = 6009
    ERROR_CLIENT_INV_NET_REPLY = 6010
    ERROR_INVALID_WORKER_REPLY = 7000
    ERROR_WORKER_OPERATION = 7001
    ERROR_PARSING_RULE = 8001
    ERROR_RULE_NOT_FOUND = 8002
    ERROR_RULE_HAS_CIRCULAR_REF = 8003
    ERROR_RULE_DIVISION_BY_ZERO = 8004
    ERROR_COMMIT_OBJECTNOTCHECKEDOUT = 9000
    ERROR_COMMIT_OBJECTCHECKEDOUT = 9001
    ERROR_COMMIT_CANTCOMMIT = 9002
    ERROR_GPU_CANCELED_READ_REQUEST = 90001
    ERROR_GPU_CANCELED_WRITE_REQUEST = 90002
    ERROR_CUDA_RUNTIME = 10000
    ERROR_GPU_MEMORY_FULL = 10001
    ERROR_STOPPED_BY_ADMIN = 10002
    ERROR_INVALID_COMMAND = 10003
    ERROR_LICENSE_EXPIRED = 11000
    ERROR_LICENSE_NOVALID = 11001
    ERROR_LICENSE_NOFREENAMED = 12000
    ERROR_LICENSE_NOKEY = 12001
    ERROR_LICENSE_NOACTCODE = 12002
    ERROR_LICENSE_ACTCODEINVALID = 12003
    ERROR_LICENSE_ALREADYACTIVATED = 12004
    ERROR_LICENSE_OVERUSED = 12005
    ERROR_LICENSE_NOAPI = 12006
    ERROR_MAX_CELL_REACHED = 12007
    ERROR_MAX_ELEM_REACHED = 12008


class OlapSession:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @SID.setter
    def SID(self) -> str: ...

    @SID.setter
    def SID(self, value: str) -> None: ...

    @property
    @TTL.setter
    def TTL(self) -> int: ...

    @TTL.setter
    def TTL(self, value: int) -> None: ...

    @property
    @Optional.setter
    def Optional(self) -> str: ...

    @Optional.setter
    def Optional(self, value: str) -> None: ...

    @property
    @UserName.setter
    def UserName(self) -> str: ...

    @UserName.setter
    def UserName(self, value: str) -> None: ...

    @property
    @Locale.setter
    def Locale(self) -> Any: ...

    @Locale.setter
    def Locale(self, value: Any) -> None: ...


#Class Methods
    def ToString(self) -> str: ...



class PicklistFilter(AdvancedFilter):
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, items: List[str]): ...

    @overload
    def __init__(self, items: Iterable[str]): ...

#Properties
    @property
    @MultiFlags.setter
    def MultiFlags(self) -> PickListFlag: ...

    @MultiFlags.setter
    def MultiFlags(self, value: PickListFlag) -> None: ...

    @property
    @Flags.setter
    def Flags(self) -> PickListFlag: ...

    @Flags.setter
    def Flags(self, value: PickListFlag) -> None: ...

    @property
    @Elements.setter
    def Elements(self) -> List[str]: ...

    @Elements.setter
    def Elements(self, value: List[str]) -> None: ...


#Class Methods
    @overload
    def Clone(self) -> PicklistFilter: ...

    def CsvSerialize(self) -> str: ...

    @staticmethod
    def op_Implicit(plf: PicklistFilter) -> str: ...



class PickListFlag(Enum):
    INSERT_BACK = 1
    MERGE = 2
    SUB = 4
    INSERT_FRONT = 8
    DFILTER = 16


class ResponseStatusCode(Enum):
    Unknown = -1
    OK = 1
    Exception = 2




class SerializationFormat(Enum):
    Auto = 0
    JSON = 1
    XML = 2


class SerializationHelper:
#Class Methods
    @staticmethod
    def Deserialize(definition: str, format: SerializationFormat) -> Any: ...

    @staticmethod
    def Serialize(value: Any, format: SerializationFormat) -> str: ...



class Server:
#Constructors
    def __init__(self, olapConnection: IOlapConnection, olapSession: IOlapSession): ...

#Properties
    @property
    @CurrentUserInfo.setter
    def CurrentUserInfo(self) -> OlapUserInfo: ...

    @property
    @IsAdmin.setter
    def IsAdmin(self) -> bool: ...

    @property
    @SystemDatabase.setter
    def SystemDatabase(self) -> Database: ...

    @property
    @Connected.setter
    def Connected(self) -> bool: ...


#Class Methods
    def ActivateLicense(self, lickey: str, actcode: str) -> bool: ...

    @overload
    def Calculate(self, cubeView: CubeView, viewParams: ViewParams) -> CalcResult: ...

    @staticmethod
    @overload
    def Calculate(server: Server, viewRequest: ViewRequest) -> CalcResult: ...

    def CalculateSubset(self, subset: DimensionSubset) -> Iterable[CalcElementInfo]: ...

    def ChangePassword(self, password: str, user: str) -> bool: ...

    def CreateDatabase(self, database_name: str) -> Database: ...

    @overload
    def Database(self, databaseInfo: DatabaseInfo) -> Database: ...

    @overload
    def Database(self, databaseId: Any) -> Database: ...

    @overload
    def Database(self, databaseName: str) -> Database: ...

    @overload
    def DatabaseInfo(self, databaseId: Any) -> DatabaseInfo: ...

    @overload
    def DatabaseInfo(self, databaseName: str) -> DatabaseInfo: ...

    def DatabaseInfos(self) -> List[DatabaseInfo]: ...

    def Databases(self) -> List[Database]: ...

    def DeleteDatabase(self, database: Any) -> bool: ...

    def Info(self) -> ServerInfo: ...

    def KillSession(self, session: IOlapSession) -> bool: ...

    def Load(self) -> bool: ...

    def RuleFunctions(self) -> Any: ...

    def Save(self, complete: bool) -> bool: ...

    def Shutdown(self) -> bool: ...

    def StopJob(self, jobId: str, session: IOlapSession) -> bool: ...

    def UnpackStored(self, subset: DimensionSubset) -> DimensionSubset: ...

    def UserInfo(self, show_permission: bool, show_info: bool) -> OlapUserInfo: ...



class SortingFilterFlag(Enum):
    TEXT = 1
    NUMERIC = 2
    USE_ATTRIBUTE = 4
    USE_ALIAS = 8
    REVERSE_ORDER = 16
    LEAVES_ONLY = 32
    STANDARD_ORDER = 64
    WHOLE = 128
    POSITION = 256
    REVERSE_TOTAL = 512
    SORT_ONE_LEVEL = 1024
    FLAT_HIERARCHY = 2048
    NO_CHILDREN = 4096
    CONSOLIDATED_ONLY = 8192
    SORT_NOT_ONE_LEVEL = 16384
    SHOW_DUPLICATES = 32768
    REVERSE_TOTAL_EX = 65536
    LIMIT = 131072
    CONSOLIDATION_ORDER = 262144
    PATH = 524288
    NOSORT = 1048576


class SortSettings:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @MultiFlags.setter
    def MultiFlags(self) -> SortingFilterFlag: ...

    @MultiFlags.setter
    def MultiFlags(self, value: SortingFilterFlag) -> None: ...

    @property
    @Flags.setter
    def Flags(self) -> SortingFilterFlag: ...

    @Flags.setter
    def Flags(self, value: SortingFilterFlag) -> None: ...

    @property
    @Indent.setter
    def Indent(self) -> IndentEnum: ...

    @Indent.setter
    def Indent(self, value: IndentEnum) -> None: ...

    @property
    @AttributeName.setter
    def AttributeName(self) -> str: ...

    @AttributeName.setter
    def AttributeName(self, value: str) -> None: ...

    @property
    @Level.setter
    def Level(self) -> Any: ...

    @Level.setter
    def Level(self, value: Any) -> None: ...

    @property
    @LimitCount.setter
    def LimitCount(self) -> Any: ...

    @LimitCount.setter
    def LimitCount(self, value: Any) -> None: ...

    @property
    @LimitStart.setter
    def LimitStart(self) -> Any: ...

    @LimitStart.setter
    def LimitStart(self, value: Any) -> None: ...


#Class Methods
    def Clone(self) -> SortSettings: ...

    @overload
    def CsvSerialize(self) -> str: ...

    @overload
    def CsvSerialize(self, ensureSingle: bool) -> str: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class StringUtils:
#Class Methods
    @staticmethod
    def Quote(str: str) -> str: ...

    @staticmethod
    def Unquote(str: str) -> str: ...



class StructuralFilterFlag(Enum):
    BELOW_INCLUSIVE = 1
    BELOW_EXCLUSIVE = 2
    HIDE_CONSOLIDATED = 4
    HIDE_LEAVES = 8
    HIERARCHIAL_LEVEL = 16
    AGGREGATED_LEVEL = 32
    REVOLVING = 64
    REVOLVE_ADD_ABOVE = 128
    REVOLVE_ADD_BELOW = 256
    ABOVE_EXCLUSIVE = 512
    ABOVE_INCLUSIVE = 1024
    CYCLIC = 2048


class SubsetSimplePick:
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @FlatSelection.setter
    def FlatSelection(self) -> Iterable[DeterminalPick]: ...

    @property
    @FlatExpanded.setter
    def FlatExpanded(self) -> Iterable[DeterminalPick]: ...

    @property
    @SeveralItems.setter
    def SeveralItems(self) -> List[DeterminalPick]: ...

    @SeveralItems.setter
    def SeveralItems(self, value: List[DeterminalPick]) -> None: ...

    @property
    @SingleItem.setter
    def SingleItem(self) -> str: ...

    @SingleItem.setter
    def SingleItem(self, value: str) -> None: ...


#Class Methods
    def Clone(self) -> SubsetSimplePick: ...

    @overload
    def CsvSerialize(self) -> str: ...

    @overload
    def CsvSerialize(self, ensureSingle: bool, sortSettings: SortSettings) -> str: ...

    def OnPropertyChanged(self, propertyName: str) -> None: ...



class TextFilter(AdvancedFilter):
#EventHandlers
    PropertyChanged: Callable[[Any, Any], None]    # void function(object sender, EventArgs args) 

#Constructors
    def __init__(self): ...

#Properties
    @property
    @MultiFlags.setter
    def MultiFlags(self) -> TextFilterFlag: ...

    @MultiFlags.setter
    def MultiFlags(self, value: TextFilterFlag) -> None: ...

    @property
    @Flags.setter
    def Flags(self) -> TextFilterFlag: ...

    @Flags.setter
    def Flags(self, value: TextFilterFlag) -> None: ...

    @property
    @Expressions.setter
    def Expressions(self) -> List[ExpressionStatement]: ...

    @Expressions.setter
    def Expressions(self, value: List[ExpressionStatement]) -> None: ...


#Class Methods
    @overload
    def Clone(self) -> TextFilter: ...

    def CsvSerialize(self) -> str: ...



class TextFilterFlag(Enum):
    ADDITIONAL_FIELDS = 1
    EXTENDED = 2


class ValueDescription:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @Value.setter
    def Value(self) -> Any: ...

    @Value.setter
    def Value(self, value: Any) -> None: ...

    @property
    @Description.setter
    def Description(self) -> str: ...

    @Description.setter
    def Description(self, value: str) -> None: ...


#Class Methods


class ViewCalculate:
#Class Methods


class ViewRequest:
#Instance variables (non-static)
    Subsets: Dict[str, List[str]]
    CustomRules: Dict[str, str]

#Constructors
    def __init__(self): ...

#Properties
    @property
    @DatabaseName.setter
    def DatabaseName(self) -> str: ...

    @DatabaseName.setter
    def DatabaseName(self, value: str) -> None: ...

    @property
    @CubeName.setter
    def CubeName(self) -> str: ...

    @CubeName.setter
    def CubeName(self, value: str) -> None: ...

    @property
    @Layout.setter
    def Layout(self) -> ViewRequestLayout: ...

    @Layout.setter
    def Layout(self, value: ViewRequestLayout) -> None: ...


#Class Methods


class ViewRequestLayout:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @Pages.setter
    def Pages(self) -> List[AxeElement]: ...

    @property
    @Columns.setter
    def Columns(self) -> List[AxeElement]: ...

    @property
    @Rows.setter
    def Rows(self) -> List[AxeElement]: ...


#Class Methods


class XmlSerializerHelper:
#Class Methods
    @staticmethod
    @overload
    def DeserializeXml(input: str) -> Any: ...

    @staticmethod
    @overload
    def DeserializeXml(s: Any) -> Any: ...

    @staticmethod
    @overload
    def DeserializeXml(input: str) -> Tuple[bool, Any]: ...

    @staticmethod
    @overload
    def DeserializeXml(input: str) -> Tuple[bool, Any, Any]: ...

    @staticmethod
    @overload
    def SerializeXml(target: Any) -> str: ...

    @staticmethod
    @overload
    def SerializeXml(target: Any, encoding: Any) -> str: ...


