'''
Stubs generated by PyStubbler version [1.0.0.0]
Date: Monday, 01 December 2025 23:55

Namespace: Planum.DAL.Model

In Assembly: Planum.DAL

'''

from typing import Tuple, Set, Iterable, List, overload, Dict, Callable, Any
from .. import DimensionSubset



class CalcElementInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @alias.setter
    def alias(self) -> str: ...

    @alias.setter
    def alias(self, value: str) -> None: ...

    @property
    @element.setter
    def element(self) -> ElementInfo: ...

    @element.setter
    def element(self, value: ElementInfo) -> None: ...

    @property
    @path.setter
    def path(self) -> str: ...

    @path.setter
    def path(self, value: str) -> None: ...


#Class Methods
    def FixIndentByPath(self) -> CalcElementInfo: ...



class CellArea:
#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, cv: CellValue, path: List[Any]): ...

    @overload
    def __init__(self, cv: CellValue, path: List[Any], isConsolidated: bool): ...

#Properties
    @property
    @type.setter
    def type(self) -> CellType: ...

    @type.setter
    def type(self, value: CellType) -> None: ...

    @property
    @exists.setter
    def exists(self) -> int: ...

    @exists.setter
    def exists(self, value: int) -> None: ...

    @property
    @value.setter
    def value(self) -> str: ...

    @value.setter
    def value(self, value: str) -> None: ...

    @property
    @path.setter
    def path(self) -> List[Any]: ...

    @path.setter
    def path(self, value: List[Any]) -> None: ...

    @property
    @rule.setter
    def rule(self) -> Any: ...

    @rule.setter
    def rule(self, value: Any) -> None: ...

    @property
    @lock_info.setter
    def lock_info(self) -> Any: ...

    @lock_info.setter
    def lock_info(self, value: Any) -> None: ...

    @property
    @property_values.setter
    def property_values(self) -> CellProperties: ...

    @property_values.setter
    def property_values(self, value: CellProperties) -> None: ...


#Class Methods
    def FormattedValue(self, locale: Any) -> str: ...



class CellProperties:
#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, capacity: int, comparer: Any): ...

#Properties

#Class Methods


class CellType(Enum):
    Numeric = 1
    String = 2
    Error = 99


class CellValue:
#Constructors
    @overload
    def __init__(self): ...

    @overload
    def __init__(self, ca: CellArea): ...

#Properties
    @property
    @type.setter
    def type(self) -> CellType: ...

    @type.setter
    def type(self, value: CellType) -> None: ...

    @property
    @exists.setter
    def exists(self) -> int: ...

    @exists.setter
    def exists(self, value: int) -> None: ...

    @property
    @value.setter
    def value(self) -> str: ...

    @value.setter
    def value(self, value: str) -> None: ...

    @property
    @rule.setter
    def rule(self) -> Any: ...

    @rule.setter
    def rule(self, value: Any) -> None: ...

    @property
    @lock_info.setter
    def lock_info(self) -> Any: ...

    @lock_info.setter
    def lock_info(self, value: Any) -> None: ...

    @property
    @property_values.setter
    def property_values(self) -> CellProperties: ...

    @property_values.setter
    def property_values(self, value: CellProperties) -> None: ...


#Class Methods
    def FormattedValue(self, locale: Any) -> str: ...



class CellValueExt:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @cv.setter
    def cv(self) -> CellValue: ...

    @cv.setter
    def cv(self, value: CellValue) -> None: ...

    @property
    @isFreezed.setter
    def isFreezed(self) -> bool: ...

    @isFreezed.setter
    def isFreezed(self, value: bool) -> None: ...

    @property
    @isConsolidated.setter
    def isConsolidated(self) -> bool: ...

    @isConsolidated.setter
    def isConsolidated(self, value: bool) -> None: ...


#Class Methods


class CubeInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @cube.setter
    def cube(self) -> Any: ...

    @cube.setter
    def cube(self, value: Any) -> None: ...

    @property
    @name_cube.setter
    def name_cube(self) -> str: ...

    @name_cube.setter
    def name_cube(self, value: str) -> None: ...

    @property
    @number_dimensions.setter
    def number_dimensions(self) -> Any: ...

    @number_dimensions.setter
    def number_dimensions(self, value: Any) -> None: ...

    @property
    @dimensions.setter
    def dimensions(self) -> List[Any]: ...

    @dimensions.setter
    def dimensions(self, value: List[Any]) -> None: ...

    @property
    @dimension_names.setter
    def dimension_names(self) -> List[str]: ...

    @dimension_names.setter
    def dimension_names(self, value: List[str]) -> None: ...

    @property
    @number_cells.setter
    def number_cells(self) -> str: ...

    @number_cells.setter
    def number_cells(self, value: str) -> None: ...

    @property
    @number_filled_cells.setter
    def number_filled_cells(self) -> str: ...

    @number_filled_cells.setter
    def number_filled_cells(self, value: str) -> None: ...

    @property
    @Status.setter
    def Status(self) -> CubeStatus: ...

    @Status.setter
    def Status(self, value: CubeStatus) -> None: ...

    @property
    @type.setter
    def type(self) -> CubeType: ...

    @type.setter
    def type(self, value: CubeType) -> None: ...

    @property
    @cube_token.setter
    def cube_token(self) -> str: ...

    @cube_token.setter
    def cube_token(self, value: str) -> None: ...

    @property
    @permission.setter
    def permission(self) -> str: ...

    @permission.setter
    def permission(self, value: str) -> None: ...

    @property
    @load_time.setter
    def load_time(self) -> Any: ...

    @load_time.setter
    def load_time(self, value: Any) -> None: ...

    @property
    @memory_size.setter
    def memory_size(self) -> Any: ...

    @memory_size.setter
    def memory_size(self, value: Any) -> None: ...

    @property
    @gpu_flag.setter
    def gpu_flag(self) -> Any: ...

    @gpu_flag.setter
    def gpu_flag(self, value: Any) -> None: ...

    @property
    @audit_days.setter
    def audit_days(self) -> Any: ...

    @audit_days.setter
    def audit_days(self, value: Any) -> None: ...


#Class Methods


class CubeStatus(Enum):
    Unloaded = 0
    Loaded = 1
    Changed = 2


class CubeType(Enum):
    Normal = 0
    System = 1
    Attribute = 2
    UserInfo = 3
    GPU = 4


class DatabaseInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @database.setter
    def database(self) -> Any: ...

    @database.setter
    def database(self, value: Any) -> None: ...

    @property
    @name_database.setter
    def name_database(self) -> str: ...

    @name_database.setter
    def name_database(self, value: str) -> None: ...

    @property
    @number_dimensions.setter
    def number_dimensions(self) -> Any: ...

    @number_dimensions.setter
    def number_dimensions(self, value: Any) -> None: ...

    @property
    @number_cubes.setter
    def number_cubes(self) -> Any: ...

    @number_cubes.setter
    def number_cubes(self, value: Any) -> None: ...

    @property
    @status.setter
    def status(self) -> DatabaseStatus: ...

    @status.setter
    def status(self, value: DatabaseStatus) -> None: ...

    @property
    @type.setter
    def type(self) -> DatabaseType: ...

    @type.setter
    def type(self, value: DatabaseType) -> None: ...

    @property
    @database_token.setter
    def database_token(self) -> str: ...

    @database_token.setter
    def database_token(self, value: str) -> None: ...

    @property
    @permission.setter
    def permission(self) -> str: ...

    @permission.setter
    def permission(self, value: str) -> None: ...

    @property
    @load_time.setter
    def load_time(self) -> Any: ...

    @load_time.setter
    def load_time(self, value: Any) -> None: ...

    @property
    @memory_size.setter
    def memory_size(self) -> Any: ...

    @memory_size.setter
    def memory_size(self, value: Any) -> None: ...

    @property
    @IsOnline.setter
    def IsOnline(self) -> bool: ...


#Class Methods


class DatabaseStatus(Enum):
    Unloaded = 0
    Loaded = 1
    Changed = 2
    Loading = 3


class DatabaseType(Enum):
    Unknown = -1
    Normal = 0
    System = 1
    UserInfo = 3


class DFilterMode(Enum):
    DATA_MIN = 1
    DATA_MAX = 2
    DATA_SUM = 4
    DATA_AVERAGE = 8
    DATA_ANY = 16
    DATA_ALL = 32
    DATA_STRING = 64
    ONLY_CONSOLIDATED = 128
    ONLY_LEAVES = 256
    UPPER_PERCENTAGE = 512
    LOWER_PERCENTAGE = 1024
    MID_PERCENTAGE = 2048
    TOP = 4096
    NORULES = 8192


class DimensionInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @dimension.setter
    def dimension(self) -> Any: ...

    @dimension.setter
    def dimension(self, value: Any) -> None: ...

    @property
    @ndimension.setter
    def ndimension(self) -> str: ...

    @ndimension.setter
    def ndimension(self, value: str) -> None: ...

    @property
    @number_elements.setter
    def number_elements(self) -> Any: ...

    @number_elements.setter
    def number_elements(self, value: Any) -> None: ...

    @property
    @maximum_level.setter
    def maximum_level(self) -> Any: ...

    @maximum_level.setter
    def maximum_level(self, value: Any) -> None: ...

    @property
    @maximum_indent.setter
    def maximum_indent(self) -> Any: ...

    @maximum_indent.setter
    def maximum_indent(self, value: Any) -> None: ...

    @property
    @maximum_depth.setter
    def maximum_depth(self) -> Any: ...

    @maximum_depth.setter
    def maximum_depth(self, value: Any) -> None: ...

    @property
    @type.setter
    def type(self) -> DimensionType: ...

    @type.setter
    def type(self, value: DimensionType) -> None: ...

    @property
    @assoc_dimension.setter
    def assoc_dimension(self) -> Any: ...

    @assoc_dimension.setter
    def assoc_dimension(self, value: Any) -> None: ...

    @property
    @attribute_cube.setter
    def attribute_cube(self) -> Any: ...

    @attribute_cube.setter
    def attribute_cube(self, value: Any) -> None: ...

    @property
    @rights_cube.setter
    def rights_cube(self) -> Any: ...

    @rights_cube.setter
    def rights_cube(self, value: Any) -> None: ...

    @property
    @dimension_token.setter
    def dimension_token(self) -> str: ...

    @dimension_token.setter
    def dimension_token(self, value: str) -> None: ...

    @property
    @permission.setter
    def permission(self) -> str: ...

    @permission.setter
    def permission(self, value: str) -> None: ...

    @property
    @load_time.setter
    def load_time(self) -> Any: ...

    @load_time.setter
    def load_time(self, value: Any) -> None: ...

    @property
    @memory_size.setter
    def memory_size(self) -> Any: ...

    @memory_size.setter
    def memory_size(self, value: Any) -> None: ...


#Class Methods


class DimensionSubsetInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @DatabaseName.setter
    def DatabaseName(self) -> str: ...

    @DatabaseName.setter
    def DatabaseName(self, value: str) -> None: ...

    @property
    @DimensionName.setter
    def DimensionName(self) -> str: ...

    @DimensionName.setter
    def DimensionName(self, value: str) -> None: ...

    @property
    @SubsetName.setter
    def SubsetName(self) -> str: ...

    @SubsetName.setter
    def SubsetName(self, value: str) -> None: ...

    @property
    @IsPrivate.setter
    def IsPrivate(self) -> Any: ...

    @IsPrivate.setter
    def IsPrivate(self, value: Any) -> None: ...

    @property
    @SubsetDefinition.setter
    def SubsetDefinition(self) -> DimensionSubset: ...

    @SubsetDefinition.setter
    def SubsetDefinition(self, value: DimensionSubset) -> None: ...


#Class Methods


class DimensionType(Enum):
    Normal = 0
    System = 1
    Attribute = 2
    UserInfo = 3
    SystemId = 4


class DrillThroughInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @ViewName.setter
    def ViewName(self) -> str: ...

    @ViewName.setter
    def ViewName(self, value: str) -> None: ...


#Class Methods


class ElementInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @element.setter
    def element(self) -> Any: ...

    @element.setter
    def element(self, value: Any) -> None: ...

    @property
    @element_name.setter
    def element_name(self) -> str: ...

    @element_name.setter
    def element_name(self, value: str) -> None: ...

    @property
    @position.setter
    def position(self) -> Any: ...

    @position.setter
    def position(self, value: Any) -> None: ...

    @property
    @level.setter
    def level(self) -> Any: ...

    @level.setter
    def level(self, value: Any) -> None: ...

    @property
    @indent.setter
    def indent(self) -> Any: ...

    @indent.setter
    def indent(self, value: Any) -> None: ...

    @property
    @depth.setter
    def depth(self) -> Any: ...

    @depth.setter
    def depth(self, value: Any) -> None: ...

    @property
    @type.setter
    def type(self) -> ElementType: ...

    @type.setter
    def type(self, value: ElementType) -> None: ...

    @property
    @number_parents.setter
    def number_parents(self) -> Any: ...

    @number_parents.setter
    def number_parents(self, value: Any) -> None: ...

    @property
    @parents.setter
    def parents(self) -> List[Any]: ...

    @parents.setter
    def parents(self, value: List[Any]) -> None: ...

    @property
    @number_children.setter
    def number_children(self) -> Any: ...

    @number_children.setter
    def number_children(self, value: Any) -> None: ...

    @property
    @children.setter
    def children(self) -> List[Any]: ...

    @children.setter
    def children(self, value: List[Any]) -> None: ...

    @property
    @weights.setter
    def weights(self) -> List[float]: ...

    @weights.setter
    def weights(self, value: List[float]) -> None: ...

    @property
    @permission.setter
    def permission(self) -> str: ...

    @permission.setter
    def permission(self, value: str) -> None: ...


#Class Methods


class ElementType(Enum):
    Unknown = 0
    Numeric = 1
    String = 2
    Consolidated = 4


class ICellArea:
#Properties
    @property
    @exists.setter
    def exists(self) -> int: ...

    @property
    @path.setter
    def path(self) -> List[Any]: ...

    @property
    @type.setter
    def type(self) -> CellType: ...

    @property
    @value.setter
    def value(self) -> str: ...


#Class Methods


class ICellValue:
#Properties
    @property
    @exists.setter
    def exists(self) -> int: ...

    @property
    @type.setter
    def type(self) -> CellType: ...

    @property
    @value.setter
    def value(self) -> str: ...


#Class Methods


class ICubeInfo:
#Properties
    @property
    @cube.setter
    def cube(self) -> Any: ...

    @property
    @dimensions.setter
    def dimensions(self) -> List[Any]: ...

    @property
    @name_cube.setter
    def name_cube(self) -> str: ...

    @property
    @number_cells.setter
    def number_cells(self) -> str: ...

    @property
    @number_dimensions.setter
    def number_dimensions(self) -> Any: ...

    @property
    @number_filled_cells.setter
    def number_filled_cells(self) -> str: ...

    @property
    @permission.setter
    def permission(self) -> str: ...

    @property
    @Status.setter
    def Status(self) -> CubeStatus: ...

    @property
    @type.setter
    def type(self) -> CubeType: ...


#Class Methods


class ICV:
#Properties
    @property
    @type.setter
    def type(self) -> CellType: ...

    @property
    @exists.setter
    def exists(self) -> int: ...

    @property
    @value.setter
    def value(self) -> str: ...

    @property
    @rule.setter
    def rule(self) -> Any: ...

    @property
    @lock_info.setter
    def lock_info(self) -> Any: ...

    @property
    @property_values.setter
    def property_values(self) -> CellProperties: ...


#Class Methods


class IDatabaseInfo:
#Properties
    @property
    @database.setter
    def database(self) -> Any: ...

    @property
    @name_database.setter
    def name_database(self) -> str: ...

    @property
    @number_cubes.setter
    def number_cubes(self) -> Any: ...

    @property
    @number_dimensions.setter
    def number_dimensions(self) -> Any: ...

    @property
    @permission.setter
    def permission(self) -> str: ...

    @property
    @status.setter
    def status(self) -> DatabaseStatus: ...

    @property
    @type.setter
    def type(self) -> DatabaseType: ...


#Class Methods


class IDimensionInfo:
#Properties
    @property
    @dimension.setter
    def dimension(self) -> Any: ...

    @property
    @maximum_depth.setter
    def maximum_depth(self) -> Any: ...

    @property
    @maximum_indent.setter
    def maximum_indent(self) -> Any: ...

    @property
    @maximum_level.setter
    def maximum_level(self) -> Any: ...

    @property
    @ndimension.setter
    def ndimension(self) -> str: ...

    @property
    @number_elements.setter
    def number_elements(self) -> Any: ...

    @property
    @permission.setter
    def permission(self) -> str: ...

    @property
    @type.setter
    def type(self) -> DimensionType: ...


#Class Methods


class IElementInfo:
#Properties
    @property
    @element.setter
    def element(self) -> Any: ...

    @property
    @element_name.setter
    def element_name(self) -> str: ...

    @property
    @position.setter
    def position(self) -> Any: ...

    @property
    @level.setter
    def level(self) -> Any: ...

    @property
    @indent.setter
    def indent(self) -> Any: ...

    @property
    @depth.setter
    def depth(self) -> Any: ...

    @property
    @type.setter
    def type(self) -> ElementType: ...

    @property
    @number_parents.setter
    def number_parents(self) -> Any: ...

    @property
    @parents.setter
    def parents(self) -> List[Any]: ...

    @property
    @number_children.setter
    def number_children(self) -> Any: ...

    @property
    @children.setter
    def children(self) -> List[Any]: ...

    @property
    @weights.setter
    def weights(self) -> List[float]: ...

    @property
    @permission.setter
    def permission(self) -> str: ...


#Class Methods


class ILockInfo:
#Properties
    @property
    @lockId.setter
    def lockId(self) -> int: ...

    @property
    @area.setter
    def area(self) -> str: ...

    @property
    @user.setter
    def user(self) -> str: ...

    @property
    @steps.setter
    def steps(self) -> int: ...


#Class Methods


class IOlapUserInfo:
#Properties
    @property
    @id.setter
    def id(self) -> int: ...

    @property
    @name.setter
    def name(self) -> str: ...

    @property
    @groups.setter
    def groups(self) -> List[int]: ...

    @property
    @group_names.setter
    def group_names(self) -> List[str]: ...

    @property
    @permission.setter
    def permission(self) -> Dict[str, str]: ...

    @permission.setter
    def permission(self, value: Dict[str, str]) -> None: ...

    @property
    @description.setter
    def description(self) -> str: ...

    @description.setter
    def description(self, value: str) -> None: ...


#Class Methods


class IRuleInfo:
#Properties
    @property
    @active.setter
    def active(self) -> bool: ...

    @property
    @comment.setter
    def comment(self) -> str: ...

    @property
    @external_identifier.setter
    def external_identifier(self) -> str: ...

    @property
    @position.setter
    def position(self) -> float: ...

    @property
    @rule.setter
    def rule(self) -> Any: ...

    @property
    @definition.setter
    def definition(self) -> str: ...

    @property
    @timestamp.setter
    def timestamp(self) -> Any: ...


#Class Methods


class IServerInfo:
#Properties
    @property
    @major_version.setter
    def major_version(self) -> str: ...

    @property
    @minor_version.setter
    def minor_version(self) -> str: ...


#Class Methods


class LockInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @lockId.setter
    def lockId(self) -> int: ...

    @lockId.setter
    def lockId(self, value: int) -> None: ...

    @property
    @area.setter
    def area(self) -> str: ...

    @area.setter
    def area(self, value: str) -> None: ...

    @property
    @user.setter
    def user(self) -> str: ...

    @user.setter
    def user(self, value: str) -> None: ...

    @property
    @steps.setter
    def steps(self) -> int: ...

    @steps.setter
    def steps(self, value: int) -> None: ...


#Class Methods
    def CubeCoordinates(self) -> Iterable[Iterable[Any]]: ...



class OlapUserInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @id.setter
    def id(self) -> int: ...

    @id.setter
    def id(self, value: int) -> None: ...

    @property
    @name.setter
    def name(self) -> str: ...

    @name.setter
    def name(self, value: str) -> None: ...

    @property
    @groups.setter
    def groups(self) -> List[int]: ...

    @groups.setter
    def groups(self, value: List[int]) -> None: ...

    @property
    @group_names.setter
    def group_names(self) -> List[str]: ...

    @group_names.setter
    def group_names(self, value: List[str]) -> None: ...

    @property
    @ttl.setter
    def ttl(self) -> int: ...

    @ttl.setter
    def ttl(self, value: int) -> None: ...

    @property
    @permission.setter
    def permission(self) -> Dict[str, str]: ...

    @permission.setter
    def permission(self, value: Dict[str, str]) -> None: ...

    @property
    @license.setter
    def license(self) -> str: ...

    @license.setter
    def license(self, value: str) -> None: ...

    @property
    @description.setter
    def description(self) -> str: ...

    @description.setter
    def description(self, value: str) -> None: ...


#Class Methods


class RuleInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @rule.setter
    def rule(self) -> Any: ...

    @rule.setter
    def rule(self, value: Any) -> None: ...

    @property
    @definition.setter
    def definition(self) -> str: ...

    @definition.setter
    def definition(self, value: str) -> None: ...

    @property
    @external_identifier.setter
    def external_identifier(self) -> str: ...

    @external_identifier.setter
    def external_identifier(self, value: str) -> None: ...

    @property
    @comment.setter
    def comment(self) -> str: ...

    @comment.setter
    def comment(self, value: str) -> None: ...

    @property
    @timestamp.setter
    def timestamp(self) -> Any: ...

    @timestamp.setter
    def timestamp(self, value: Any) -> None: ...

    @property
    @active.setter
    def active(self) -> bool: ...

    @active.setter
    def active(self, value: bool) -> None: ...

    @property
    @position.setter
    def position(self) -> float: ...

    @position.setter
    def position(self, value: float) -> None: ...


#Class Methods


class SelectableDimensionSubsetInfo(DimensionSubsetInfo):
#Constructors
    def __init__(self): ...

#Properties
    @property
    @IsSelected.setter
    def IsSelected(self) -> bool: ...

    @IsSelected.setter
    def IsSelected(self, value: bool) -> None: ...

    @property
    @SubsetId.setter
    def SubsetId(self) -> str: ...

    @SubsetId.setter
    def SubsetId(self, value: str) -> None: ...

    @property
    @IsGenerated.setter
    def IsGenerated(self) -> bool: ...

    @IsGenerated.setter
    def IsGenerated(self, value: bool) -> None: ...


#Class Methods


class ServerInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @major_version.setter
    def major_version(self) -> str: ...

    @major_version.setter
    def major_version(self, value: str) -> None: ...

    @property
    @minor_version.setter
    def minor_version(self) -> str: ...

    @minor_version.setter
    def minor_version(self, value: str) -> None: ...

    @property
    @encryption.setter
    def encryption(self) -> str: ...

    @encryption.setter
    def encryption(self, value: str) -> None: ...

    @property
    @https_port.setter
    def https_port(self) -> str: ...

    @https_port.setter
    def https_port(self, value: str) -> None: ...

    @property
    @data_token.setter
    def data_token(self) -> str: ...

    @data_token.setter
    def data_token(self, value: str) -> None: ...

    @property
    @delay_loading.setter
    def delay_loading(self) -> str: ...

    @delay_loading.setter
    def delay_loading(self, value: str) -> None: ...

    @property
    @uptime.setter
    def uptime(self) -> str: ...

    @uptime.setter
    def uptime(self, value: str) -> None: ...

    @property
    @load_time.setter
    def load_time(self) -> str: ...

    @load_time.setter
    def load_time(self, value: str) -> None: ...

    @property
    @memory_size.setter
    def memory_size(self) -> str: ...

    @memory_size.setter
    def memory_size(self, value: str) -> None: ...


#Class Methods


class SplashType(Enum):
    NoSplashing = 0
    Default = 1
    Add = 2
    Set = 3


class StoredCubeViewInfo:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @DatabaseName.setter
    def DatabaseName(self) -> str: ...

    @DatabaseName.setter
    def DatabaseName(self, value: str) -> None: ...

    @property
    @CubeName.setter
    def CubeName(self) -> str: ...

    @CubeName.setter
    def CubeName(self, value: str) -> None: ...

    @property
    @ViewName.setter
    def ViewName(self) -> str: ...

    @ViewName.setter
    def ViewName(self, value: str) -> None: ...

    @property
    @IsPrivate.setter
    def IsPrivate(self) -> bool: ...

    @IsPrivate.setter
    def IsPrivate(self, value: bool) -> None: ...

    @property
    @ViewParams.setter
    def ViewParams(self) -> ViewParams: ...

    @ViewParams.setter
    def ViewParams(self, value: ViewParams) -> None: ...


#Class Methods


class UserInfo(OlapUserInfo):
#Constructors
    def __init__(self, userInfo: OlapUserInfo): ...

#Properties
    @property
    @AccessToken.setter
    def AccessToken(self) -> str: ...

    @AccessToken.setter
    def AccessToken(self, value: str) -> None: ...

    @property
    @RefreshToken.setter
    def RefreshToken(self) -> str: ...

    @RefreshToken.setter
    def RefreshToken(self, value: str) -> None: ...

    @property
    @Properties.setter
    def Properties(self) -> Dict[str, str]: ...

    @Properties.setter
    def Properties(self, value: Dict[str, str]) -> None: ...


#Class Methods


class ViewParams:
#Constructors
    def __init__(self): ...

#Properties

#Class Methods

