'''
Stubs generated by PyStubbler version [1.0.0.0]
Date: Monday, 01 December 2025 23:55

Namespace: Planum.Applications

In Assembly: Planum.DAL

'''

from typing import Tuple, Set, Iterable, List, overload, Dict, Callable, Any
from ..DAL import Server, IOlapConnection



class JobProperties:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @Name.setter
    def Name(self) -> str: ...

    @Name.setter
    def Name(self, value: str) -> None: ...

    @property
    @Duration.setter
    def Duration(self) -> str: ...

    @Duration.setter
    def Duration(self, value: str) -> None: ...

    @property
    @Properties.setter
    def Properties(self) -> str: ...

    @Properties.setter
    def Properties(self, value: str) -> None: ...

    @property
    @Command.setter
    def Command(self) -> str: ...

    @Command.setter
    def Command(self, value: str) -> None: ...


#Class Methods


class Jobs:
#Properties
    @property
    @Session.setter
    def Session(self) -> str: ...

    @Session.setter
    def Session(self, value: str) -> None: ...

    @property
    @Job.setter
    def Job(self) -> str: ...

    @Job.setter
    def Job(self, value: str) -> None: ...

    @property
    @Properties.setter
    def Properties(self) -> JobProperties: ...

    @Properties.setter
    def Properties(self, value: JobProperties) -> None: ...


#Class Methods
    @staticmethod
    def GetJobs(server: Server) -> Iterable[Jobs]: ...



class SessionProperties:
#Constructors
    def __init__(self): ...

#Properties
    @property
    @User.setter
    def User(self) -> str: ...

    @User.setter
    def User(self, value: str) -> None: ...

    @property
    @Jobs.setter
    def Jobs(self) -> str: ...

    @Jobs.setter
    def Jobs(self, value: str) -> None: ...

    @property
    @LoginTime.setter
    def LoginTime(self) -> str: ...

    @LoginTime.setter
    def LoginTime(self, value: str) -> None: ...

    @property
    @ExpirationTime.setter
    def ExpirationTime(self) -> str: ...

    @ExpirationTime.setter
    def ExpirationTime(self, value: str) -> None: ...

    @property
    @Time.setter
    def Time(self) -> str: ...

    @Time.setter
    def Time(self, value: str) -> None: ...

    @property
    @ActiveJobs.setter
    def ActiveJobs(self) -> str: ...

    @ActiveJobs.setter
    def ActiveJobs(self, value: str) -> None: ...

    @property
    @License.setter
    def License(self) -> str: ...

    @License.setter
    def License(self, value: str) -> None: ...

    @property
    @Address.setter
    def Address(self) -> str: ...

    @Address.setter
    def Address(self, value: str) -> None: ...

    @property
    @Command.setter
    def Command(self) -> str: ...

    @Command.setter
    def Command(self, value: str) -> None: ...

    @property
    @Description.setter
    def Description(self) -> str: ...

    @Description.setter
    def Description(self, value: str) -> None: ...

    @property
    @MachineId.setter
    def MachineId(self) -> str: ...

    @MachineId.setter
    def MachineId(self, value: str) -> None: ...

    @property
    @CurrentSession.setter
    def CurrentSession(self) -> bool: ...

    @CurrentSession.setter
    def CurrentSession(self, value: bool) -> None: ...


#Class Methods


class Sessions:
#Properties
    @property
    @Sid.setter
    def Sid(self) -> str: ...

    @Sid.setter
    def Sid(self, value: str) -> None: ...

    @property
    @Properties.setter
    def Properties(self) -> SessionProperties: ...

    @Properties.setter
    def Properties(self, value: SessionProperties) -> None: ...


#Class Methods
    @staticmethod
    def GetSessions(server: Server) -> Iterable[Sessions]: ...

    def Kill(self, olapConnection: IOlapConnection) -> None: ...


